import { Database, Search, FileText, Server, Sparkles, Layers } from "lucide-react"
import type { Resource } from "./types"

export const resources: Resource[] = [
  {
    id: "blob",
    name: "Azure Blob Storage",
    icon: Database,
    iconClass: "bg-sky-50 text-sky-600",
    health: "healthy",
    avgLatency: "120ms",
    successRate: 100,
    tests: [
      {
        id: "blob-1",
        name: "SDK Access (Programmatic)",
        status: "passed",
        duration: "120ms",
        lastRun: "14:32:18",
        message: "Successfully connected and listed containers",
      },
      {
        id: "blob-2",
        name: "Mounted Access",
        status: "passed",
        duration: "30ms",
        lastRun: "14:32:18",
        message: "Read test file from mounted path",
      },
    ],
  },
  {
    id: "search",
    name: "Azure AI Search",
    icon: Search,
    iconClass: "bg-indigo-50 text-indigo-600",
    health: "healthy",
    avgLatency: "283ms",
    successRate: 100,
    tests: [
      {
        id: "search-1",
        name: "Search Query",
        status: "passed",
        duration: "250ms",
        lastRun: "14:32:17",
        message: "Search returned 5 results",
      },
      {
        id: "search-2",
        name: "Index Document",
        status: "passed",
        duration: "400ms",
        lastRun: "14:32:16",
        message: "Document indexed successfully",
      },
      {
        id: "search-3",
        name: "Delete Document",
        status: "passed",
        duration: "200ms",
        lastRun: "14:32:16",
        message: "Document deleted successfully",
      },
    ],
  },
  {
    id: "docint",
    name: "Azure Document Intelligence",
    icon: FileText,
    iconClass: "bg-violet-50 text-violet-600",
    health: "degraded",
    avgLatency: "1.8s",
    successRate: 67,
    tests: [
      {
        id: "docint-1",
        name: "Analyze Document (PDF)",
        status: "passed",
        duration: "1.6s",
        lastRun: "14:32:16",
        message: "Document analyzed successfully",
      },
      {
        id: "docint-2",
        name: "Extract Fields",
        status: "passed",
        duration: "210ms",
        lastRun: "14:32:15",
        message: "Extracted 12 fields",
      },
      {
        id: "docint-3",
        name: "Custom Model (Invoice)",
        status: "failed",
        duration: "2.1s",
        lastRun: "14:32:15",
        message: "Model returned confidence below threshold",
      },
    ],
  },
  {
    id: "postgres",
    name: "Azure PostgreSQL",
    icon: Server,
    iconClass: "bg-blue-50 text-blue-700",
    health: "healthy",
    avgLatency: "95ms",
    successRate: 100,
    tests: [
      {
        id: "pg-1",
        name: "Connection",
        status: "passed",
        duration: "45ms",
        lastRun: "14:32:15",
        message: "Successfully connected",
      },
      {
        id: "pg-2",
        name: "Read (SELECT 1)",
        status: "passed",
        duration: "25ms",
        lastRun: "14:32:15",
        message: "Query executed successfully",
      },
      {
        id: "pg-3",
        name: "Write (Insert)",
        status: "passed",
        duration: "60ms",
        lastRun: "14:32:14",
        message: "Row inserted successfully",
      },
      {
        id: "pg-4",
        name: "Delete (Cleanup)",
        status: "passed",
        duration: "55ms",
        lastRun: "14:32:14",
        message: "Row deleted successfully",
      },
    ],
  },
  {
    id: "openai",
    name: "Azure OpenAI",
    icon: Sparkles,
    iconClass: "bg-emerald-50 text-emerald-600",
    health: "unhealthy",
    avgLatency: "1.6s",
    successRate: 60,
    tests: [
      {
        id: "openai-1",
        name: "Chat Completion (gpt-4o)",
        status: "passed",
        duration: "1.3s",
        lastRun: "14:32:14",
        message: "Received valid completion",
      },
      {
        id: "openai-2",
        name: "Responses API",
        status: "failed",
        duration: "812ms",
        lastRun: "14:32:13",
        message: "401 Unauthorized",
      },
      {
        id: "openai-3",
        name: "Embeddings",
        status: "passed",
        duration: "620ms",
        lastRun: "14:32:13",
        message: "Received vector of length 1536",
      },
      {
        id: "openai-4",
        name: "Streaming Completion",
        status: "passed",
        duration: "1.8s",
        lastRun: "14:32:12",
        message: "Stream completed successfully",
      },
      {
        id: "openai-5",
        name: "Structured Output (JSON)",
        status: "failed",
        duration: "1.2s",
        lastRun: "14:32:12",
        message: "Invalid JSON in response",
      },
    ],
  },
  {
    id: "redis",
    name: "Azure Redis Cache",
    icon: Layers,
    iconClass: "bg-red-50 text-red-600",
    health: "healthy",
    avgLatency: "40ms",
    successRate: 100,
    tests: [
      {
        id: "redis-1",
        name: "Connection",
        status: "passed",
        duration: "20ms",
        lastRun: "14:32:11",
        message: "Successfully connected",
      },
      {
        id: "redis-2",
        name: "SET / GET",
        status: "passed",
        duration: "40ms",
        lastRun: "14:32:11",
        message: "Value set and retrieved",
      },
    ],
  },
]
